const ShopActionConstants = {
	FETCH_COLLECTIONS_PENDING: 'FETCH_COLLECTIONS_PENDING',
	FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
	FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
};

export default ShopActionConstants;