const CartActionConsts = {
	TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	SUBTRACT_ITEM: 'SUBTRACT_ITEM',
	REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
	CLEAR_CART: 'CLEAR_CART'
};

export default CartActionConsts;