const UserActionConstants = {
	// SET_CURRENT_USER: 'SET_CURRENT_USER',
	EMAIL_LOG_IN_PENDING: 'EMAIL_LOG_IN_PENDING',
	GOOGLE_LOG_IN_PENDING: 'GOOGLE_LOG_IN_PENDING',
	LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
	LOG_IN_FAILURE: 'LOG_IN_FAILURE',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	LOG_OUT_PENDING: 'LOG_OUT_PENDING',
	LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
	LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
	REGISTER_PENDING: 'REGISTER_PENDING',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAILURE: 'REGISTER_FAILURE'
};

export default UserActionConstants;